wsp = _{ ( " " | "\t" ) }
nl = _{ "\n" }

ident = @{ ('a'..'z' | 'A'..'Z' | '0'..'9' | "_")+ }

param = { ident }
params = _{ param ~ wsp* ~ ","? ~ wsp* }

template_params = _{ "(" ~ params* ~ ")" } 
template_decl = _{ ident ~ template_params? ~ wsp* ~ "::=" ~ wsp+ ~ "<<" ~ nl? }
template_terminator = _{ ">>" }
template_content = { (!template_terminator ~ any)* }
template = _{ template_decl ~ nl? ~ template_content ~ template_terminator }

file = _{ soi ~ (template | nl)* ~ eoi }
